//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studynung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryResult
    {
        public int Id { get; set; }
        public string Results { get; set; }
        public string Errors { get; set; }
    
        public virtual LaboratoryProcess LaboratoryProcess { get; set; }
    }
}
