//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studynung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryProcess
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public int UserId { get; set; }
        public int LaboratoryWorkId { get; set; }
    
        public virtual User User { get; set; }
        public virtual LaboratoryResult LaboratoryResult { get; set; }
        public virtual LaboratoryWork LaboratoryWork { get; set; }
    }
}
