//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studynung.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudynungContainer : DbContext
    {
        public StudynungContainer()
            : base("name=StudynungContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<StudentInfo> StudentInfoes { get; set; }
        public DbSet<TeacherInfo> TeacherInfoes { get; set; }
        public DbSet<Cathedra> Cathedras { get; set; }
        public DbSet<AcademicGroup> AcademicGroups { get; set; }
        public DbSet<LaboratoryWork> LaboratoryWorks { get; set; }
        public DbSet<LaboratoryProcess> LaboratoryProcesses { get; set; }
        public DbSet<LaboratoryResult> LaboratoryResults { get; set; }
    }
}
